stages:
  - test
  - build

test:
  stage: test
  tags: 
      - docker
  image: golang:1.17
  script: 
   - go test .

build:
  stage: build
  tags: 
      - docker
  image: docker:latest
  script:
   - docker build .
