stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test ./dvps-materials-gitlab

build:
  stage: build
  image: docker:latest
  script:
   - docker build ./sdvps-materials-gitlab
